package com.gerasimchuk.utils;

public enum MessageCode {

    ERROR_CARGO_DATA_TRANSFER_OBJECT_VALIDATION_FAILED,



    ERROR_CITY_FROM_IS_NULL,


    ERROR_CITY_TO_IS_NULL,

    ERROR_CITIES_FROM_AND_TO_ARE_EQUAL,


    SUCCESS_CARGO_CREATED,

    SUCCESS_CARGO_UPDATED,

    SUCCESS_CARGO_DELETED,

    ERROR_ROUTE_NOT_EXIST,

    ERROR_CAN_NOT_PARSE_ID,

    ERROR_ID_VALUE_IS_ZERO,

    ERROR_CAN_NOT_CHANGE_CARGO_WITH_ASSIGNED_ORDER,

    ERROR_CARGO_ID_FIELD_IN_DATA_TRANSFER_OBJECT_IS_NULL_OR_EMPTY,

    ERROR_CARGO_ID_IS_NOT_VALID,

    ERROR_NO_SUCH_CARGO_IN_DATABASE,

    ERROR_CAN_NOT_DELETE_EXECUTING_CARGO,


}
